services:
  synapse:
    image: matrixdotorg/synapse:v1.131.0
    restart: unless-stopped
    networks:
      synapse_extras_network:
        gw_priority: 0
      tipi_main_network:
        gw_priority: 1
    volumes:
        - ${APP_DATA_DIR}/data/synapse:/data
    ports:
      - ${APP_PORT}:8008
    labels:
      runtipi.managed: true
      runtipi.appurn: synapse:extras
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true
  synapse_extras_network:
    external: false
    ipam:
      config:
        - subnet: 10.128.11.0/24

